language: ruby
rvm:
  - 1.9.3
  - 2.0.0
notifications:
  email:
    recipients:
      - "michael@psu.edu"
    on_success: "change"
    on_failure: "always"
  irc:
    channels:
      - "irc.freenode.org#scholarsphere"
    template:
      - "%{repository}//%{branch}@%{commit} by %{author}: %{message} - %{build_url}"